### ISSUE TITLE
create sticker set function error

### ISSUE THREAD

**Issue by makusujp** [star-39/moe-sticker-bot#14]
when you create the package using /create_sticker_set
then after you set the name and ID string, upload the zip files for png images(tested webp also failed)

`Traceback (most recent call last):
  File "/home/user1/Downloads/moe-sticker-bot/main.py", line 311, in parse_emoji
    do_auto_create_sticker_set(update, ctx)
  File "/home/user1/Downloads/moe-sticker-bot/main.py", line 58, in do_auto_create_sticker_set
    ctx.user_data['telegram_sticker_files'] = ctx.user_data['line_queue'].get(timeout=300)
AttributeError: 'NoneType' object has no attribute 'get'`

already rebuild the debian11 for python3.10.3, + mariadb10.7.3 but still with latest release(git clone again) 
now the bot even not able to start 
but still with above issue
I also test your official one but it went well.

can you point out where is the issue come from?

**Comment by makusujp** [comment]
pulled to https://github.com/star-39/moe-sticker-bot/commit/a4b5db839704409bf4ce1e88d55d9c7bfbcd68a6
and yes the issue of /create_sticker_set has been cleared
thank you for your hard working!
