### ISSUE TITLE
無法使用

### ISSUE THREAD

**Issue by wei711071** [star-39/moe-sticker-bot#4]
Traceback (most recent call last):
  File "/moe-sticker-bot-master/main.py", line 555, in prepare_tg_sticker
    ctx.bot.get_file(sticker.file_id).download(os.path.join(sticker_dir,
  File "/usr/local/lib/python3.9/dist-packages/telegram/files/file.py", line 175, in download
    fobj.write(buf)
OSError: [Errno 28] No space left on device

**Comment by star-39** [comment]
謝謝反饋! 我現在正在修復這個問題.
