### ISSUE TITLE
the animate stickers runs with Fatal error result

### ISSUE THREAD

**Issue by makusujp** [star-39/moe-sticker-bot#8]
I self host the bot by clone in debian11.1
previously the bot works fine.
the animated sticker just goes to the static pictures.

this update I deleted the whole moe-sticker-bot folder,
and recheck install of the requirement.
but the bot returns this result below

`Traceback (most recent call last):
  File "/home/debian/Downloads/moe-sticker-bot/helper.py", line 41, in retry_do
    func()
  File "/home/debian/Downloads/moe-sticker-bot/main.py", line 71, in ＜lambda＞
    err = retry_do(lambda: ctx.bot.create_new_sticker_set(user_id=update.effective_user.id,
  File "/home/debian/.local/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
TypeError: create_new_sticker_set() got an unexpected keyword argument 'webm_sticker'`

and i tested once at your official one works.
does the requirements added something new but not listed?

**Comment by makusujp** [comment]
thanks 
that upgrade did help
